name: dpre1
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - rdkit
  - scikit-learn
  - chembl_webresource_client
  - vina
  - meeko
  - prolif
  - openbabel
  - pandas
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - streamlit
  - joblib
  - pip
  - pip:
    - chembl-webresource-client
